<?php
header("content-type:text/html;charset=gb2312");
session_start();
define("ROOT",dirname(__FILE__));
set_include_path(".".PATH_SEPARATOR.ROOT."/lib".PATH_SEPARATOR.ROOT."/core".PATH_SEPARATOR.ROOT."/configs".PATH_SEPARATOR.get_include_path());
require_once 'mysql.func.php';
require_once 'images.func.php';
require_once 'common.func.php';
require_once 'string.func.php';
require_once 'page.func.php';
require_once 'configs.php';
require_once 'admin.inc.php';
require_once 'user.inc.php';
require_once 'focus.inc.php';
require_once 'teaminfo.inc.php';
require_once 'blog.inc.php';
require_once 'contact.inc.php';
require_once 'album.inc.php';
require_once 'houses.inc.php';
require_once 'comment.inc.php';
connect();